services:
  database:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - root-password

secrets:
  api-key:
    file: ./src/api/api-key.txt
  root-password:
    file: ./src/database/root-password.txt

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mariadb_data
