services:
  database:
    container_name: baseTodiPelis
    image: todipelis_base
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/root-password
      - MARIADB_USER=api
      - MARIADB_PASSWORD_FILE=/run/secrets/api-password
      - MARIADB_DATABASE=todipelis
    build:
      context: ./src/database
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - root-password
      - api-password
    networks:
      - todipelis-network

  api:
    container_name: apiTodiPelis
    image: todipelis_api
    environment:
      - FLASK_APP=ApiTodiPelis/app.py
      - FLASK_RUN_PORT=5000
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    secrets:
      - api-key
      - api-password
    depends_on:
      - database
    networks:
      - todipelis-network

secrets:
  api-key:
    file: ./src/api/api-key.txt
  root-password:
    file: ./src/database/root-password.txt
  api-password:
    file: ./src/database/api-password.txt

volumes:
  db_data:
    name: folderDatosTodiPelis
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mariadb_data

networks:
  todipelis-network:
    driver: bridge
