services:
  database:
    container_name: baseTodiPelis
    image: todipelis_base
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/root-password
      - MARIADB_USER=api
      - MARIADB_PASSWORD_FILE=/run/secrets/api-password
      - MARIADB_DATABASE=todipelis
    build:
      context: ./src/database
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - root-password
      - api-password

secrets:
  api-key:
    file: ./src/api/api-key.txt
  root-password:
    file: ./src/database/root-password.txt
  api-password:
    file: ./src/database/api-password.txt

volumes:
  db_data:
    name: folderDatosTodiPelis
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mariadb_data
